name: Build LLVM XCFrameworks for Release
on:
    workflow_dispatch:
jobs:
  build-llvm-xcframework:
    runs-on: macos-latest
    timeout-minutes: 600
    steps:
      - uses: actions/checkout@v3
      - name: Build LLVM for all platforms
        timeout-minutes: 600
        run: |
          ./build-tools.sh
          export PATH=$PATH:`pwd`/tools/bin
          ./build-llvm-framework.sh macosx iphoneos iphonesimulator maccatalyst appletvos appletvsimulator
      - uses: actions/upload-artifact@v3
        with:
          name: LLVM.xcframework
          path: LLVM.xcframework.tar.xz
